### ISSUE TITLE
Parcel collection: Server ends connection with 1011 but client gets 1005 (with keep alive off)

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-internet-gateway#296]
This may actually be two separate issues.

Given a collection with keep alive off and one outgoing parcel:

- The server is ending the connection with a `1011` due to a "Client failure". That happens after sending the parcel to the client but before an ACK is received.
- Ktor on the client is ending the connection because either the PoWeb client or the server sent a `1005` to its peer.

Server logs:

```
[
  {
    "insertId": "dbjtxng48z3dw7",
    "jsonPayload": {
      "hostname": "gw-test-relaynet-internet-gateway-poweb-c754f748f-5zx7x",
      "peerGatewayAddress": "<redacted>",
      "msg": "Sending parcel",
      "pid": 6,
      "level": 30,
      "parcelObjectKey": "parcels/gateway-bound/<redacted>/<redacted>/<redacted>/39ef5ad3753dc7d0b25dfd734d85ba1cd91d6541cfadf17ad4393f7c7a09cf29",
      "reqId": "fa4b8734aac99f0aeb2bb8fe066af2d5/12532018683185456542"
    },
    "resource": {
      "type": "k8s_container",
      "labels": {
        "pod_name": "gw-test-relaynet-internet-gateway-poweb-c754f748f-5zx7x",
        "container_name": "poweb",
        "project_id": "public-gw",
        "namespace_name": "default",
        "cluster_name": "gateway-example",
        "location": "europe-west2-a"
      }
    },
    "timestamp": "2020-11-24T15:03:14.546Z",
    "severity": "INFO",
    "labels": {
      "compute.googleapis.com/resource_name": "gke-gateway-example-relaynet-gateway--e9096053-9qs9",
      "k8s-pod/app_kubernetes_io/instance": "gw-test",
      "k8s-pod/app_kubernetes_io/component": "poweb",
      "k8s-pod/app_kubernetes_io/name": "relaynet-internet-gateway",
      "k8s-pod/pod-template-hash": "c754f748f"
    },
    "logName": "projects/public-gw/logs/stdout",
    "receiveTimestamp": "2020-11-24T15:03:19.016243138Z"
  },
  {
    "insertId": "dbjtxng48z3dw8",
    "jsonPayload": {
      "msg": "Closing connection",
      "pid": 6,
      "closeCode": 1011,
      "level": 30,
      "reqId": "fa4b8734aac99f0aeb2bb8fe066af2d5/12532018683185456542",
      "closeReason": "Client failure",
      "hostname": "gw-test-relaynet-internet-gateway-poweb-c754f748f-5zx7x"
    },
    "resource": {
      "type": "k8s_container",
      "labels": {
        "location": "europe-west2-a",
        "project_id": "public-gw",
        "cluster_name": "gateway-example",
        "namespace_name": "default",
        "pod_name": "gw-test-relaynet-internet-gateway-poweb-c754f748f-5zx7x",
        "container_name": "poweb"
      }
    },
    "timestamp": "2020-11-24T15:03:14.753Z",
    "severity": "INFO",
    "labels": {
      "k8s-pod/app_kubernetes_io/instance": "gw-test",
      "k8s-pod/app_kubernetes_io/component": "poweb",
      "compute.googleapis.com/resource_name": "gke-gateway-example-relaynet-gateway--e9096053-9qs9",
      "k8s-pod/app_kubernetes_io/name": "relaynet-internet-gateway",
      "k8s-pod/pod-template-hash": "c754f748f"
    },
    "logName": "projects/public-gw/logs/stdout",
    "receiveTimestamp": "2020-11-24T15:03:19.016243138Z"
  }
]
```

Client traceback:

```
    java.util.concurrent.CancellationException: ActorCoroutine was cancelled
        at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
        at kotlinx.coroutines.channels.ActorCoroutine.onCancelling(Actor.kt:134)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:332)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:916)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:875)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:840)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.lang.IllegalArgumentException: Code 1005 is reserved and may not be used.
        at okhttp3.internal.ws.WebSocketProtocol.validateCloseCode(WebSocketProtocol.kt:134)
        at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.kt:435)
        at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.kt:427)
        at io.ktor.client.engine.okhttp.OkHttpWebsocketSession$outgoing$1.invokeSuspend(OkHttpWebsocketSession.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) 
```

**Comment by gnarea** [comment]
Sergio just got the following exception on the client, which looks similar to the one above but itns't quite the same:

```
2020-11-27 13:16:06.249 19838-19874/tech.relaycorp.gateway E/llectParcelsFromGateway: Could not collect parcel due to unexpected error
    java.util.concurrent.CancellationException: WebSocket session closed with code 1005.
```

**Comment by gnarea** [comment]
This turned out to be a bug in ktor: https://youtrack.jetbrains.com/issue/KTOR-1374
