### ISSUE TITLE
PoWeb crashes when trying to send parcel to client after WS connection is closed

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-internet-gateway#463]
https://console.cloud.google.com/errors/CPyauKi4uIy8YQ?project=relaycorp-cloud-gateway

Unfortunately, the traceback is useless:

```
Error: WebSocket is not open: readyState 3 (CLOSED)
    at sendAfterClose (/opt/gw/node_modules/ws/lib/websocket.js:754:17)
    at WebSocket.send (/opt/gw/node_modules/ws/lib/websocket.js:345:7)
    at Duplex.duplex._write (/opt/gw/node_modules/ws/lib/stream.js:157:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Duplex.Writable.write (_stream_writable.js:318:11)
    at Object.sink (/opt/gw/node_modules/stream-to-it/sink.js:71:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

But [the logs](https://cloudlogging.app.goo.gl/TM9x1ghpEZ3QyT9A9) do show that a parcel was attempted to be sent 40ms after the connection was closed.

![logs](https://user-images.githubusercontent.com/369863/113602504-9959c980-963a-11eb-81a9-11bcc961bc7b.png)

**Comment by gnarea** [comment]
This could have the same root cause as https://github.com/relaycorp/awala-gateway-desktop/issues/365

**Comment by gnarea** [comment]
There are two bug fixes in this `ws` release that sound like they could address this issue: https://github.com/websockets/ws/releases/tag/7.5.3

**Comment by gnarea** [comment]
ws v7.5.3 didn't fix this issue: It happened again with relaynet-internet-gateway v1.24.47, which had those fixes.
