### ISSUE TITLE
Functional tests in CI stopped working between 31st August and 11th September

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-internet-gateway#630]
And it's still broken:

```
FAIL src/functionalTests/internet_e2e.test.ts (16.645 s)
  ● Sending pings via PoWeb and receiving pongs via PoHTTP

    : Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 10000 ms timeout specified by jest.setTimeout.Error:

      36 | import { generatePdaChain, IS_GITHUB, sleep } from './utils';
      37 | 
    > 38 | test('Sending pings via PoWeb and receiving pongs via PoHTTP', async () => {
         | ^
      39 |   const powebClient = PoWebClient.initLocal(GW_POWEB_LOCAL_PORT);
      40 |   const gwPDAChain = await generatePdaChain();
      41 |   const privateGatewaySigner = new Signer(

      at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Object.<anonymous> (internet_e2e.test.ts:38:1)

  ● Sending pings via CogRPC and receiving pongs via PoHTTP

    expect(received).toHaveLength(expected)

    Expected length: 2
    Received length: 1
    Received array:  [[]]

      113 |     expect(collectedCargoes).toHaveLength(1);
      114 |     const collectedMessages = await extractMessagesFromCargo(collectedCargoes[0], pdaChain);
    > 115 |     expect(collectedMessages).toHaveLength(2);
          |                               ^
      116 |     expect(ParcelCollectionAck.deserialize(collectedMessages[0])).toHaveProperty(
      117 |       'parcelId',
      118 |       pingParcelData.parcelId,

      at Object.<anonymous> (internet_e2e.test.ts:115:31)
```

**Comment by gnarea** [comment]
It turned out to be caused by a bug (https://github.com/relaycorp/relaynet-core-js/pull/325), which happened to be triggered by a recent change in Cloudflare's DoH resolver.
